name: odiya_news_app
description: "Pulp News - Your trusted source for fresh, summarized local news in your language. Stay informed with the latest stories from credible sources, carefully curated and presented in short, easy-to-read summaries."
publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.1.0
  # dio: ^5.9.0
  # pretty_dio_logger: ^1.4.0
  # get_it: ^8.2.0
  get: ^4.7.2
  firebase_auth: ^6.0.1
  shared_preferences: ^2.5.3
  firebase_core: ^4.0.0
  cloud_functions: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # cached_network_image: ^3.3.1
  share_plus: ^10.0.2
  url_launcher: ^6.3.1
  # flutter_localizations:
  #   sdk: flutter
  intl: ^0.20.2
  flutter_svg: ^2.2.1
  google_mobile_ads: ^6.0.0
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  webview_flutter: ^4.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: "^0.14.4"
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_logo.png
    - assets/icons/app_logo.svg
    - assets/icons/explore_logo.svg
    - assets/in.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"
  adaptive_icon_background: "#ffffff"

